# Generated by Django 5.1.5 on 2025-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordereditem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
