# Generated by Django 5.1.5 on 2025-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordereditem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
